### ISSUE TITLE
windows build

### ISSUE THREAD

**Issue by benjaminlewandowski** [sefrijn/traktor-library-manager#2]
hi, i tried to build the project under windows as well as in wsl2 but i cant get a stable build

**Comment by sefrijn** [comment]
Hi @benjaminlewandowski ,
I haven't tried building the project myself on WIndows. I've developed and build it on Mac only.
Maybe I can help if you have specific questions or issues?

**Comment by benjaminlewandowski** [comment]
Hi @sefrijn jast saw your really quick reply and wanted to thank you.

steps it took where:

- clone the repo
- fix the wrong filenames (as some where lowercase and wsl/ubuntu is case sensetive) 
- add the config.js file with spotify information
- run the build command with `vue-cli-service electron:build --windows`

the result is a installer that runs (so the nsis part seems working) but an installed instance which throws an error on starting

![Screenshot 2022-05-24 153303](https://user-images.githubusercontent.com/64488529/170047686-1e3b59e7-6953-4d2f-84fb-65e9a9ee72b3.png)

building for macos and running it on my mbp works without problems (but as i only use my windows machine for djaying this won't really help me)

thanks in advance!

**Comment by benjaminlewandowski** [comment]
removed my locally installed node version on windows and used the portable one inside of [laragon](https://laragon.org) and the build worked inside windows.

building inside linux/macos with --windows still
